Update OEP: Add eval_js method
Banuba/OEP-desktop pull request #13
Opened 2022-06-27 19:12 UTC by bn-roma

Also format script was used, so there are a few format editions

2022-06-28 11:51 UTC, sdk-banuba requested changes

2022-06-28 11:51 UTC, sdk-banuba commented on effect_player.hpp
> +    class js_callback: public bnb::interfaces::js_callback
Лучше перенести этот класс в .cpp файл

2022-06-28 11:51 UTC, sdk-banuba commented on effect_player.cpp
> +                auto callback = std::make_shared<bnb::oep::js_callback>(result_callback);
здесь нужно сделать так:

std::shared_ptr<js_callback> callback = result_callback ? std::make_shared<js_callback>(result_callback) : nullptr;

2022-06-28 11:51 UTC, sdk-banuba commented on effect_player.hpp
> +            : m_callback(std::move(callback)) {};
Здесь можно добавить пустую строку после {};

2022-06-28 11:51 UTC, sdk-banuba commented on effect_player.hpp
> +        void on_result(const std::string & result) override;
И после этого тоже пустую строку

2022-06-28 11:51 UTC, sdk-banuba commented on effect_player.cpp
> +    bool effect_player::eval_js(const std::string& script, const oep_eval_js_result_cb& result_callback)
void effect_player::eval_js(const std::string& script, const oep_eval_js_result_cb& result_callback)

2022-06-28 11:51 UTC, sdk-banuba commented on effect_player.cpp
> +                return false;
убрать все return

2022-06-28 13:11 UTC, sdk-banuba approved these changes

2022-06-28 13:35 UTC, dmitrystoyanovsky commented on effect_player.cpp
> +        js_callback(const oep_eval_js_result_cb& callback)
why do we need a reference here? I think it is better to pass by value and move to the class member.

2022-06-29 10:18 UTC, dmitrystoyanovsky requested changes

2022-06-29 13:28 UTC, dmitrystoyanovsky approved these changes

2022-06-30 07:07 UTC, merged