refactoring libraries folder
Banuba/OEP-desktop pull request #18
Opened 2022-08-19 07:13 UTC by sdk-banuba

2022-08-19 13:10 UTC, dmitrystoyanovsky requested changes

2022-08-19 13:10 UTC, dmitrystoyanovsky commented on libraries/renderer/render_thread.cpp
> +} /* namespace bnb::render */
Please apply the style of Banuba SDK by applying ./scripts/reformat.py --docker
- Copy code to the Banuba SDK folder
- Update reformat script to process copied folder
- Run script
- Copy changed files back.

2022-08-19 13:10 UTC, dmitrystoyanovsky commented on libraries/renderer/render_thread.cpp
> +} /* namespace bnb::render */
To mark the end of namespace '}' it is used the // comment style (one line)

2022-08-19 13:10 UTC, dmitrystoyanovsky commented on libraries/renderer/renderer.cpp
> -// RGBA texture
Please recheck that change - it seems you made the wrong one.

2022-08-19 13:10 UTC, dmitrystoyanovsky commented on libraries/renderer/renderer.cpp
> -    // NOTE: The shader below assumes that texture image is oriented head at the top, so it inverts y-axis
Wrong change - recheck

2022-08-19 13:10 UTC, dmitrystoyanovsky commented on libraries/utils/glfw_utils/glfw_window.cpp
> +    /* glfw_window::glfw_window */
I think such comments are excessive, please reconsider their usage - I'd prefer to remove them to make the style closer to SDK.

2022-08-22 07:02 UTC, closed without merging

2022-08-22 07:02 UTC, sdk-banuba commented
this PR is incorrect, based on incorrect branch